# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # environment: main
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore Dopamine.sln
    - name: Build
      run: msbuild Dopamine.sln /p:Configuration=Release

    - name: Bundle Artifact
      uses: vimtor/action-zip@v1.2
      with:
        files: D:\a\dopamine-windows\dopamine-windows\Dopamine\bin\Release\
        dest: Dopamine.portable.unstable.${{ github.sha }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_executable
        path: D:\a\dopamine-windows\dopamine-windows\dopamine\bin\Release\Dopamine.portable.unstable.${{ github.sha }}.zip
        if-no-files-found: error
